### ISSUE TITLE
Quand on clique sur le bouton "Demande de profil worker"

### ISSUE THREAD

**Issue by cheikhahmedt** [cheikhahmedt/monprojet#3]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 242, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 702, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 368, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 357, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 925, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 546, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1324, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1316, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 471, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 456, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6541, in onchange
    result['value'] = snapshot1.diff(snapshot0, force=first_call)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6365, in diff
    result[name] = field.convert_to_onchange(self[name], record, {})
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2854, in convert_to_onchange
    return super().convert_to_onchange(value._origin, record, names)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 890, in convert_to_onchange
    return self.convert_to_read(value, record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2830, in convert_to_read
    return value.id
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 658, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: '_unknown' object has no attribute 'id'

**Comment by cheikhahmedt** [comment]
l'erreur venait de cette ligne message_follower_ids = fields.One2many(
        'mail.followers', 'res_id', string='Followers', groups='base.group_user'). Il fallait rajouter une dependance vers `mail`
